#Makefile
JCC = javac
JFLAGS = -g -Xlint
default: GetURL.class Stock.class StockServerInterface.class StockServer.class User.class

GetURL.class: GetURL.java
	$(JCC) $(JFLAGS) GetURL.java
Stock.class: Stock.java
	$(JCC) $(JFLAGS) Stock.java
StockServerInterface.class: StockServerInterface.java
	$(JCC) $(JFLAGS) StockServerInterface.java
StockServer.class: StockServer.java 
	$(JCC) $(JFLAGS) StockServer.java 
User.class: User.java 
	$(JCC) $(JFLAGS) User.java 
