#Makefile
JCC = javac
JFLAGS = -g -Xlint
default: GetURL.class StockClient.class StockServerInterface.class Stock.class User.class

GetURL.class: GetURL.java
	$(JCC) $(JFLAGS) GetURL.java
StockClient.class: StockClient.java
	$(JCC) $(JFLAGS) StockClient.java
Stock.class: Stock.java
	$(JCC) $(JFLAGS) Stock.java
StockServerInterface.class: StockServerInterface.java
	$(JCC) $(JFLAGS) StockServerInterface.java
User.class: User.java 
	$(JCC) $(JFLAGS) User.java 
